# Generated by Django 5.0.1 on 2024-05-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_ordering_app', '0002_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='menuItem',
            new_name='menuitem',
        ),
    ]
