# Generated by Django 5.0.1 on 2024-05-21 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_ordering_app', '0003_rename_menuitem_cartitem_menuitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('total_price', models.IntegerField(default=0)),
                ('in_cart', models.BooleanField(default=True)),
                ('placed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_ordering_app.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('extra', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, max_length=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Food_ordering_app.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_ordering_app.menuitem')),
                ('toppings', models.ManyToManyField(blank=True, related_name='pizza', to='Food_ordering_app.pizzatopping')),
            ],
        ),
    ]
