# Generated by Django 5.0.1 on 2024-05-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_ordering_app', '0004_alter_menuitem_price_alter_menuitem_size_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
