# Generated by Django 5.0.1 on 2024-06-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_ordering_app', '0007_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pizzatopping',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
