# Generated by Django 5.0.1 on 2024-06-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_ordering_app', '0009_alter_cartitem_quantity_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
    ]
