# Generated by Django 5.0.1 on 2024-06-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_ordering_app', '0010_remove_cart_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
