# Generated by Django 5.0.1 on 2024-06-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_ordering_app', '0011_remove_menuitem_extra_remove_menuitem_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
