# Generated by Django 5.0.1 on 2024-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_ordering_app', '0012_remove_orderitem_extra_remove_orderitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='pizza',
            new_name='menuitem',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='oredr_items', to='Food_ordering_app.pizzatopping'),
        ),
    ]
