# Generated by Django 5.0.1 on 2024-06-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_ordering_app', '0019_alter_shippinginformation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
