# Generated by Django 5.0.1 on 2025-01-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_ordering_app', '0021_alter_menuitem_image_alter_menuitem_pizza_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
